---
title: "Italian Wine Analysis"
author: "Divyanshu Marwah"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load_packages, echo=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(MCMCpack)
```
```{r load_data}
wine <- read.csv("https://www.scss.tcd.ie/~arwhite/Teaching/CS7DS3/winemag-data-130k-v2.csv")
head(wine)
```
```{r}
summary(wine)
dim(wine)
```

## converting factors to character columns for data wrangling and sampling purposes
```{r}
i <- sapply(wine, is.factor)
wine[i] <- lapply(wine[i], as.character)
head(wine)
```


```{r}
italy_group <- subset(wine, country =='Italy' & region_1!=""& price <20,select=c(region_1,country,variety,points))
head(italy_group)
```
```{r  filtered_reviews}
#italy_group %>% group_by(variety) %>% summarise(count = n())  %>% filter(count>=4)

#italy_filter_reviews <- italy_group %>% group_by(region_1) %>% filter(n()>=4)
italy_review_count <- table(italy_group$region_1)
italy_filter_reviews <- subset(italy_group,italy_group$region_1  %in% names(italy_review_count[italy_review_count>4]))
droplevels(italy_filter_reviews)
summary(italy_filter_reviews)
dim(italy_filter_reviews)
``` 

```{r}
head(italy_filter_reviews)
```
```{r}
j <- sapply(italy_filter_reviews, is.character)
italy_filter_reviews[j] <- lapply(italy_filter_reviews[j], as.factor)
head(italy_filter_reviews)
```
```{r}
ggplot(italy_filter_reviews) + geom_boxplot(aes(x = reorder(region_1, points, median), points,
fill = reorder(region_1, points, median)), show.legend=FALSE)
```
```{r}
ggplot(italy_filter_reviews, aes(x = reorder(region_1, points, median))) + stat_count()
```
```{r}
ggplot(italy_filter_reviews, aes(points)) + stat_bin()
```
```{r}
ggplot(data.frame(size = tapply(italy_filter_reviews$points, italy_filter_reviews$variety, length),
mean_score = tapply(italy_filter_reviews$points, italy_filter_reviews$variety, mean)), aes(size, mean_score)) +
geom_point() + xlab("variety sample size") + ylab("Mean points") +
ggtitle("Effect size versus sample size")
```

```{r}
ggplot(data.frame(size = tapply(italy_filter_reviews$points, italy_filter_reviews$region_1, length),
mean_score = tapply(italy_filter_reviews$points, italy_filter_reviews$region_1, mean)), aes(size, mean_score)) +
geom_point() + xlab("Regions sample size") + ylab("Mean points") +
ggtitle("Effect size versus sample size")
```


```{r gibbs_sampler}
compare_m_gibbs <- function(y, ind, mu0 = 50, tau0 = 1/100,
a0 = 1, b0 = 50, alpha0 =1, beta0 = 50, maxiter = 5000)
{
### weakly informative priors
a0 <- 1 ; b0 <- 20 ## tau_w hyperparameters
alpha0 <-1 ; beta0 <- 50 ## tau_b hyperparameters
mu0<-80 ; tau0 <- 1/25
###
### starting values
m <- nlevels(ind)
ybar <- theta <- tapply(y, ind, mean)
tau_w <- mean(1 / tapply(y, ind, var)) ##within group precision
mu <- mean(theta)
tau_b <-var(theta) ##between group precision
n_m <- tapply(y, ind, length)
alphan <- alpha0 + sum(n_m)/2
###
### setup MCMC
theta_mat <- matrix(0, nrow=maxiter, ncol=m)
mat_store <- matrix(0, nrow=maxiter, ncol=3)
###
### MCMC algorithm
for(s in 1:maxiter)
{
# sample new values of the thetas
for(j in 1:m)
{
taun <- n_m[j] * tau_w + tau_b
thetan <- (ybar[j] * n_m[j] * tau_w + mu * tau_b) / taun
theta[j]<-rnorm(1, thetan, 1/sqrt(taun))
}
#sample new value of tau_w
ss <- 0
for(j in 1:m){
ss <- ss + sum((y[ind == j] - theta[j])^2)
}
betan <- beta0 + ss/2
tau_w <- rgamma(1, alphan, betan)
#sample a new value of mu
taum <- m * tau_b + tau0
mum <- (mean(theta) * m * tau_b + mu0 * tau0) / taum
mu <- rnorm(1, mum, 1/ sqrt(taum))
# sample a new value of tau_b
am <- a0 + m/2
bm <- b0 + sum((theta - mu)^2) / 2
tau_b <- rgamma(1, am, bm)
#store results
theta_mat[s,] <- theta
mat_store[s, ] <- c(mu, tau_w, tau_b)
}
colnames(mat_store) <- c("mu", "tau_w", "tau_b")
return(list(params = mat_store, theta = theta_mat))
}
```



```{r}
fit2 <- compare_m_gibbs(italy_filter_reviews$points, italy_filter_reviews$region_1)
```
```{r}
apply(fit2$params, 2, mean)
```
```{r}
apply(fit2$params, 2, sd)
```
```{r}
mean(1/sqrt(fit2$params[, 2]))
```
```{r}
sd(1/sqrt(fit2$params[, 2]))
```
```{r}
mean(1/sqrt(fit2$params[, 3]))
```
```{r}
sd(1/sqrt(fit2$params[, 3]))
```
```{r}
theta_hat <- apply(fit2$theta, 2, mean) ## get basic posterior summary
names(theta_hat) <- 1:142 ## keep track of different regions
sort(theta_hat, decreasing = TRUE) ## which regions did best and worst?
```
```{r}
theta_df <- data.frame(samples = as.numeric(fit2$theta),
region_1 <- rep(1:ncol(fit2$theta), each = nrow(fit2$theta)))
ggplot(theta_df) + geom_boxplot(aes(x = reorder(region_1, samples, median), samples,
fill = reorder(region_1, samples, median)), show.legend=FALSE)
```
```{r}
ggplot(data.frame(size = tapply(italy_filter_reviews$points, italy_filter_reviews$region_1, length), theta_hat = theta_hat),
aes(size, theta_hat)) + geom_point()
```
```{r}
final_result<-data.frame(ybar = tapply(italy_filter_reviews$points, italy_filter_reviews$region_1, mean), theta_hat = theta_hat)
head(final_result)
```
```{r}
ggplot(data.frame(ybar = tapply(italy_filter_reviews$points, italy_filter_reviews$region_1, mean), theta_hat = theta_hat),
aes(ybar, theta_hat)) + geom_point()
```
```{r}
write.csv(final_result,"italy_analysis.csv",row.names=TRUE)
```
```{r}
mean_val<- mean(final_result$theta_hat)
more_than_avg <- subset(final_result,theta_hat>mean_val)
more_than_avg
```

```{r}
count(final_result)
```

```{r}
write.csv(more_than_avg,"italy_soln.csv",row.names = TRUE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
